feat(component): Notification
action-is-hope/shelley pull request #123
Opened 2023-06-29 15:26 UTC by 2creative

Issue: https://github.com/action-is-hope/shelley/issues/121

2023-07-25 14:07 UTC, LucjaWszola commented on src/Notification/index.ts
> +export * from "./Notification";
just missing an empty line

2023-07-25 14:07 UTC, LucjaWszola commented on src/styles/default/notification.st.css
> +}
empty line

2023-07-25 14:07 UTC, LucjaWszola commented on src/styles/shelley/notification.st.css
> +}
empty line

2023-07-25 14:09 UTC, LucjaWszola commented
Hey @2creative, it looks good, few empty lines missing.
Also, RTL does not seem to be working... possible to fix it?

2023-07-25 19:53 UTC, LucjaWszola approved these changes

2023-07-26 10:49 UTC, andreadsw commented
Hi @2creative, It looks good. The testing code looks amazing. There is a lot of effort. I have only one question before I approve. Is there a way to improve the icon's font size? It looks small at mom. What do you think?   

![Notification-Icon](https://github.com/action-is-hope/shelley/assets/4622610/e11bf468-2046-42b7-8750-df7f8a868140)


![Notification-Icon-2em](https://github.com/action-is-hope/shelley/assets/4622610/acc37bb8-7fc8-41b4-a3a1-ab69e9de01e9)

2023-07-26 11:01 UTC, 2creative commented
> Hi @2creative, It looks good. The testing code looks amazing. There is a lot of effort. I have only one question before I approve. Is there a way to improve the icon's font size? It looks small at mom. What do you think?
> 
> ![Notification-Icon](https://user-images.githubusercontent.com/4622610/256207328-e11bf468-2046-42b7-8750-df7f8a868140.png)
> 
> ![Notification-Icon-2em](https://user-images.githubusercontent.com/4622610/256207403-acc37bb8-7fc8-41b4-a3a1-ab69e9de01e9.png)

Thanks @andreadsw I just made the icon size same as the toast component size to be consistent.

2023-07-26 11:05 UTC, andreadsw approved these changes
Cool. 🎉 Thank you for clarifying. It looks good for me.

2023-07-26 13:23 UTC, GaxZE requested changes
@2creative can we add the documentation for the different variations. Currently every single one is:

```
<Notification />
``

2023-07-26 13:28 UTC, 2creative commented
> documentation

Which file are you referring to?

2023-07-26 13:32 UTC, GaxZE commented
@2creative hit code on that screenshot.

2023-07-26 15:49 UTC, 2creative commented
> @2creative hit `show code` on that screenshot.
> 
> See Button for example: ![Screenshot 2023-07-26 at 14 47 52](https://user-images.githubusercontent.com/171002/256251979-9f388ab9-9ca8-4151-90be-a40e7c306b50.png) ![Screenshot 2023-07-26 at 14 47 45](https://user-images.githubusercontent.com/171002/256251998-82fb4ea5-b9cc-4bb2-a267-96ec357c89af.png)

Thanks for looking. Updated the source examples.

2023-07-27 08:27 UTC, merged